eureka:
  server :
     enableSelfPreservation: false
  instance:
    hostname: localhost
    posrt: 8761
  client:
    registerWithEureka: false
    fetchRegistry: false
    register-with-eureka: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      defaultZone: http://localhost:8761/eureka/
      
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
